# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsCartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('product_name', models.TextField()),
                ('product_price', models.FloatField()),
                ('user_id', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'ns_cart_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ns_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsOptions',
            fields=[
                ('options_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ns_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsProductColors',
            fields=[
                ('product_color_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.BigIntegerField()),
                ('color_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ns_product_colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsProductOptions',
            fields=[
                ('product_options_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('option_group_id', models.IntegerField()),
                ('option_price_increment', models.FloatField()),
            ],
            options={
                'db_table': 'ns_product_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsProducts',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_sku', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_weight', models.CharField(max_length=50)),
                ('product_cart_desc', models.TextField()),
                ('product_short_desc', models.TextField()),
                ('product_long_desc', models.TextField()),
                ('product_thumb', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=255)),
                ('product_category_id', models.IntegerField()),
                ('product_sub_category_id', models.IntegerField()),
                ('product_sub_sub_category_id', models.IntegerField()),
                ('modified_date', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('tags', models.TextField()),
            ],
            options={
                'db_table': 'ns_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsProductSizes',
            fields=[
                ('product_size_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size_id', models.IntegerField()),
                ('product_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ns_product_sizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsSubCategory',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('sub_category_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ns_sub_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsSubSubCategory',
            fields=[
                ('sub_sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('sub_sub_category_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ns_sub_sub_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NsUsers',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=50)),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=50)),
                ('user_zip', models.IntegerField()),
                ('user_email_auth', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_address', models.TextField()),
                ('user_country', models.CharField(max_length=50)),
                ('user_status', models.IntegerField()),
            ],
            options={
                'db_table': 'ns_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('product_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'product_image',
                'managed': False,
            },
        ),
    ]
